version: '3'
services:
  web:
    build: .
    ports:
     - "8887:8887"
    command: python app.py
    depends_on:
      - mongodb
  redis:
    image: "redis"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
